name: running build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container: rust:1.86-bullseye

    steps:
    - uses: actions/checkout@v4

    - name: setup env
      run: cp -f .env.ci .env

    - name: Build
      run: cargo build

    - name: Run tests
      run: cargo test
