name: frontend jobs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths: # comment this out if you are updating actions and need to test
      - 'frontend/**'

jobs:
  check-lint-format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v4

    - run: git diff --name-status  -- path/to/directory/

    - name: Setup
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - run: npm ci
    - run: npm run lint
    - run: npm run check-format
    
